(() => {
 const K='puzzle-empire-v2'; let state=load(), current, board=[], selected=null, power=0, busy=false, booster=null, townTab='decor', townSelection=null, installPrompt=null;
 const TOWN_DECOR=[['flower','🌷','Tulips',1],['tree','🌳','Oak tree',3],['bench','🪑','Garden bench',6],['lamp','🏮','Lantern',9],['fountain','⛲','Tiny fountain',14],['market','🛒','Market stall',20],['arch','🌸','Blossom arch',27]];
 const TOWN_FRIENDS=[['luma','🧙‍♀️','Luma',1,'I can make the flowers sparkle!'],['rook','🦊','Rook',4,'The best trails begin at home.'],['pip','👑','Pip',10,'A beautiful town makes a happy kingdom.'],['moss','🧑‍🌾','Moss',18,'I will tend every garden.'],['nori','🧝','Nori',26,'I brought moonlight for the lanterns.']];
 const TOWN_PETS=[['sprig','🐶','Sprig',2,'A cheerful puppy'],['pepper','🐱','Pepper',7,'A curious cat'],['puff','🐰','Puff',13,'A cloud-soft rabbit'],['spark','🐦','Spark',21,'A bluebird with big ideas'],['mochi','🦔','Mochi',30,'A tiny garden helper']];
 const AVATARS=['🌟','🧙‍♀️','🦊','👑','🐶','🐱','🐰','🐦'];
 const BORDERS=[['blue','Blue',0],['red','Red',0],['green','Green',0],['pink','Pink',0],['gold','Gold',10],['violet','Violet',20],['rainbow','Rainbow',30]];
 const $=id=>document.getElementById(id); const el=(tag,cls,txt)=>{let n=document.createElement(tag);n.className=cls||'';n.textContent=txt||'';return n};
 function load(){const defaults={unlocked:1,coins:120,gems:15,lives:5,lastLife:Date.now(),stars:{},buildings:[],profile:{name:'Player',avatar:'🌟',border:'blue'},town:{decor:{},friends:['luma'],pets:[]}};try{let saved=JSON.parse(localStorage.getItem(K))||{};return {...defaults,...saved,profile:{...defaults.profile,...saved.profile},town:{...defaults.town,...saved.town,decor:saved.town?.decor||{},friends:saved.town?.friends||['luma'],pets:saved.town?.pets||[]}}}catch{return defaults}} function save(){localStorage.setItem(K,JSON.stringify(state));renderHUD()}
 function replenish(){let n=Math.floor((Date.now()-state.lastLife)/180000);if(n&&state.lives<5){state.lives=Math.min(5,state.lives+n);state.lastLife+=n*180000;save()}}
 function renderHUD(){replenish();$('life-display').textContent=`♥ ${state.lives}/5`;$('coin-display').textContent=state.coins;$('gem-display').textContent=state.gems;$('profile-name').textContent=state.profile.name;$('profile-avatar').textContent=state.profile.avatar;$('profile-badge').className=`profile-badge border-${state.profile.border}`}
 function show(screen){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(screen).classList.add('active')}
 function renderMap(){renderHUD();let total=Object.values(state.stars).reduce((a,b)=>a+b,0);$('map-stars').textContent=`★ ${total} / 90`;$('kingdom-progress').textContent=`${state.buildings.length} / ${BUILDINGS.length} renovations`;$('kingdom-buildings').replaceChildren(...BUILDINGS.map((b,i)=>{let x=el('div','building '+(state.buildings.includes(i)?'':'locked'),b[0]);x.innerHTML+=`<small>${b[1]}</small>`;return x}));let m=$('level-map');m.replaceChildren(...LEVELS.map(l=>{let b=el('button','level '+(l.id<=state.unlocked?'unlocked ':'')+(state.stars[l.id]?'done':''),l.id);let s=state.stars[l.id]||0;b.dataset.stars=s?'★'.repeat(s):'';b.disabled=l.id>state.unlocked;b.onclick=()=>start(l.id);return b}));}
 function start(id){replenish();if(!state.lives){modal('<h2>Out of lives</h2><p>Lives regenerate every 3 minutes in this prototype.</p><button onclick="document.getElementById(\'modal\').classList.add(\'hidden\')">Okay</button>');return} current=LEVELS[id-1];state.lives--;save();board=[];selected=null;power=0;booster=null;for(let r=0;r<8;r++){board[r]=[];for(let c=0;c<8;c++){let g;do{g=Math.floor(Math.random()*6)}while((c>1&&board[r][c-1]?.gem===g&&board[r][c-2]?.gem===g)||(r>1&&board[r-1][c]?.gem===g&&board[r-2][c]?.gem===g));board[r][c]={gem:g,special:null}}} $('level-number').textContent=id;$('goal-text').textContent=`Collect ${current.target} ${GEM_ICONS[current.targetGem]}`;$('moves-left').textContent=current.moves;$('goal-count').textContent=`0 / ${current.target}`;$('goal-fill').style.width='0%';$('companion-name').textContent=current.companion;$('companion').textContent=current.companion==='Luma'?'🧙‍♀️':current.companion==='Rook'?'🦊':'👑';$('companion-line').textContent=current.companion==='Luma'?'A little sparkle goes a long way.':'Let’s make this kingdom shine!';$('power-fill').style.width='0%';$('royal-power').disabled=true;$('hint-text').textContent='Swap adjacent gems to make a match!';renderBoard();show('game-screen')}
 function renderBoard(){if(current?.type&&current.type!=='match'){renderMini();return}let root=$('board');root.className='board';root.replaceChildren();board.flat().forEach((v,i)=>{let r=Math.floor(i/8),c=i%8,b=el('button','gem'+(selected?.r===r&&selected?.c===c?' selected':'')+(v.special?' special':''),v.special==='rainbow'?'🌈':v.special==='bomb'?'💥':GEM_ICONS[v.gem]);b.onclick=()=>tap(r,c);root.append(b)})}
 function miniShell(label){let root=$('board');root.className='mini-board';root.replaceChildren();$('goal-text').textContent=CHALLENGE_LABELS[current.type];$('hint-text').innerHTML=`<span class="challenge-type">${label}</span>`;$('moves-left').textContent='—';$('goal-count').textContent='Town challenge';$('goal-fill').style.width='100%';return root}
 function renderMini(){if(current.type==='cards')return memoryGame();if(current.type==='jigsaw')return jigsawGame();return wordGame()}
 function memoryGame(){let root=miniShell('MEMORY MATCH');let grid=el('div','memory-grid'),icons=['🌱','🌱','🪵','🪵','🏵️','🏵️','🏮','🏮','🫐','🫐','🧶','🧶'].sort(()=>Math.random()-.5);let open=[],found=0;icons.forEach(icon=>{let b=el('button','memory-card','❔');b.onclick=()=>{if(open.length===2||b.classList.contains('done'))return;b.textContent=icon;b.classList.add('revealed');open.push([b,icon]);if(open.length===2){if(open[0][1]===open[1][1]){open.forEach(x=>x[0].className='memory-card done');found++;open=[];if(found===6)setTimeout(()=>win(12),250)}else setTimeout(()=>{open.forEach(x=>{x[0].textContent='❔';x[0].classList.remove('revealed')});open=[]},550)}};grid.append(b)});root.append(grid)}
 function jigsawGame(){let root=miniShell('RESTORATION JIGSAW');let grid=el('div','jigsaw-grid'),tiles=['🏰','🌳','⛲','🌷','🧙‍♀️','🦊','🏮','🐶',''];for(let turn=0;turn<30;turn++){let empty=tiles.indexOf(''),r=Math.floor(empty/3),c=empty%3,options=[];if(r)options.push(empty-3);if(r<2)options.push(empty+3);if(c)options.push(empty-1);if(c<2)options.push(empty+1);let swapWith=options[Math.floor(Math.random()*options.length)];[tiles[empty],tiles[swapWith]]=[tiles[swapWith],tiles[empty]]}function draw(){grid.replaceChildren();tiles.forEach((tile,i)=>{let b=el('button','jigsaw-piece '+(!tile?'empty':''),tile);b.onclick=()=>{let empty=tiles.indexOf('');if(Math.abs(Math.floor(i/3)-Math.floor(empty/3))+Math.abs(i%3-empty%3)!==1)return;[tiles[i],tiles[empty]]=[tiles[empty],tiles[i]];draw();if(tiles.join('')==='🏰🌳⛲🌷🧙‍♀️🦊🏮🐶')setTimeout(()=>win(10),250)};grid.append(b)})}draw();root.append(grid)}
 function wordGame(){let root=miniShell('TOWN WORD');let words=[['TULIP','A flower for your town'],['LANTERN','It lights a garden path'],['FOUNTAIN','A centerpiece that splashes'],['ORCHARD','A home for fruit trees'],['KINGDOM','What you are restoring']];let [answer,clue]=words[(current.id-1)%words.length],picked=[];let box=el('div','word-game');box.append(el('p','word-clue',clue));let slots=el('div','word-slots','_ '.repeat(answer.length));let bank=el('div','letter-bank');answer.split('').sort(()=>Math.random()-.5).forEach(letter=>{let b=el('button','',letter);b.onclick=()=>{picked.push(letter);b.disabled=true;slots.textContent=picked.join(' ')+' '+'_ '.repeat(answer.length-picked.length);if(picked.length===answer.length){if(picked.join('')===answer)setTimeout(()=>win(10),150);else{picked=[];slots.textContent='_ '.repeat(answer.length);bank.querySelectorAll('button').forEach(x=>x.disabled=false)}}};bank.append(b)});box.append(slots,bank,el('p','mini-progress','Tap letters in the right order.'));root.append(box)}
 function tap(r,c){if(busy)return;if(booster){useBooster(r,c);return}if(!selected){selected={r,c};renderBoard();return}if(selected.r===r&&selected.c===c){selected=null;renderBoard();return}if(Math.abs(selected.r-r)+Math.abs(selected.c-c)!==1){selected={r,c};renderBoard();return}swap(selected,{r,c});let matches=findMatches();if(!matches.length){swap(selected,{r,c});$('hint-text').textContent='That swap needs a match!';selected=null;renderBoard();return}selected=null;resolve(matches)}
 function swap(a,b){[board[a.r][a.c],board[b.r][b.c]]=[board[b.r][b.c],board[a.r][a.c]]}
 function findMatches(){let out=new Set(), groups=[];for(let r=0;r<8;r++){let st=0;for(let c=1;c<=8;c++)if(c<8&&board[r][c].gem===board[r][st].gem){}else{if(c-st>=3)groups.push(Array.from({length:c-st},(_,i)=>[r,st+i]));st=c}}for(let c=0;c<8;c++){let st=0;for(let r=1;r<=8;r++)if(r<8&&board[r][c].gem===board[st][c].gem){}else{if(r-st>=3)groups.push(Array.from({length:r-st},(_,i)=>[st+i,c]));st=r}}groups.forEach(g=>g.forEach(([r,c])=>out.add(r+','+c)));return [...out].map(x=>x.split(',').map(Number))}
 function resolve(matches){busy=true;let collected=0;matches.forEach(([r,c])=>{if(board[r][c].gem===current.targetGem)collected++;board[r][c].gone=true});let total=Number($('goal-count').textContent.split(' / ')[0])+collected;$('goal-count').textContent=`${total} / ${current.target}`;$('goal-fill').style.width=Math.min(100,total/current.target*100)+'%';power=Math.min(100,power+matches.length*3);$('power-fill').style.width=power+'%';$('royal-power').disabled=power<100;let moves=Number($('moves-left').textContent)-1;$('moves-left').textContent=moves;matches.forEach(([r,c])=>{let v=board[r][c];if(v.gone){v.gem=-1;v.gone=false}});setTimeout(()=>{drop();renderBoard();setTimeout(()=>{let next=findMatches();if(next.length)resolveCascade(next,total,moves);else{busy=false;if(total>=current.target)win(moves);else if(moves<=0)lose();}},220)},170)}
 function resolveCascade(matches){let collected=0;matches.forEach(([r,c])=>{if(board[r][c].gem===current.targetGem)collected++;board[r][c].gem=-1});let total=Number($('goal-count').textContent.split(' / ')[0])+collected;$('goal-count').textContent=`${total} / ${current.target}`;$('goal-fill').style.width=Math.min(100,total/current.target*100)+'%';power=Math.min(100,power+matches.length*3);$('power-fill').style.width=power+'%';$('royal-power').disabled=power<100;setTimeout(()=>{drop();renderBoard();setTimeout(()=>{let n=findMatches();if(n) {if(n.length)resolveCascade(n);else {busy=false;if(total>=current.target)win(Number($('moves-left').textContent));}}},180)},120)}
 function drop(){for(let c=0;c<8;c++){let col=[];for(let r=7;r>=0;r--)if(board[r][c].gem>=0)col.push(board[r][c]);for(let r=7;r>=0;r--)board[r][c]=col.shift()||{gem:Math.floor(Math.random()*6),special:null}}}
 function unlockTownContent(level){let found=[];TOWN_DECOR.forEach(x=>{if(x[3]===level)found.push(`new decor: ${x[2]}`)});TOWN_FRIENDS.forEach(x=>{if(x[3]===level&&!state.town.friends.includes(x[0])){state.town.friends.push(x[0]);found.push(`new friend: ${x[2]}`)}});TOWN_PETS.forEach(x=>{if(x[3]===level&&!state.town.pets.includes(x[0])){state.town.pets.push(x[0]);found.push(`new pet: ${x[2]}`)}});return found}
 function win(moves){let stars=moves>10?3:moves>4?2:1;state.stars[current.id]=Math.max(state.stars[current.id]||0,stars);state.coins+=20+stars*10;if(current.id===state.unlocked&&current.id<30)state.unlocked++;BUILDINGS.forEach((b,i)=>{if(current.id>=b[2]&&!state.buildings.includes(i))state.buildings.push(i)});let townRewards=unlockTownContent(current.id);save();modal(`<div class="star-row">${'★'.repeat(stars)}${'☆'.repeat(3-stars)}</div><h2>Level complete!</h2><p>+ ${20+stars*10} coins · ${current.name} restored${townRewards.length?`<br><b>Town reward — ${townRewards.join(' · ')}</b>`:''}</p><button onclick="window.PE.next()">Next level</button><button class="secondary" onclick="window.PE.town()">Visit town</button><button class="secondary" onclick="window.PE.map()">Map</button>`)}function lose(){modal('<h2>Almost!</h2><p>The kingdom needs a little more magic.</p><button onclick="window.PE.retry()">Try again</button><button class="secondary" onclick="window.PE.map()">Map</button>')}
 function modal(s){$('modal-content').innerHTML=s;$('modal').classList.remove('hidden')}
 function useBooster(r,c){if(booster==='hammer'){board[r][c].gem=-1;drop();renderBoard();$('hint-text').textContent='Hammered!';}else{let g=board[r][c].gem;board.flat().forEach(x=>{if(x.gem===g)x.gem=-1});drop();renderBoard();$('hint-text').textContent='A royal color clear!'}booster=null;document.querySelectorAll('.booster').forEach(x=>x.classList.remove('selected'))}
 function unlocked(item,type){return type==='decor'?state.unlocked>=item[3]:type==='friends'?state.town.friends.includes(item[0]):state.town.pets.includes(item[0])}
 function renderTown(){let earned=Math.max(1,state.unlocked);$('town-level').textContent=Math.ceil(earned/5);let grid=$('town-grid');grid.replaceChildren(...Array.from({length:42},(_,i)=>{let plot=el('button','plot');let item=state.town.decor[i];if(item){let d=TOWN_DECOR.find(x=>x[0]===item);plot.innerHTML=`<span class="placed">${d?.[1]||''}</span>`}plot.onclick=()=>placeDecor(i);return plot}));let people=$('town-people');people.replaceChildren(...TOWN_FRIENDS.filter(x=>state.town.friends.includes(x[0])).map((x,i)=>walker(x,'resident',i)));let pets=$('town-pets');pets.replaceChildren(...TOWN_PETS.filter(x=>state.town.pets.includes(x[0])).map((x,i)=>walker(x,'pet',i)));renderInventory()}
 function walker(item,kind,i){let usesPortrait=['luma','rook','pip'].includes(item[0]);let n=el('button',kind+(usesPortrait?` town-portrait portrait-${item[0]}`:''),usesPortrait?'':item[1]);n.style.left=(usesPortrait?(item[0]==='luma'?15:item[0]==='rook'?46:75):(10+i*19))+'%';n.style.top=(usesPortrait?'38':(16+(i%3)*25))+'%';n.style.setProperty('--walk',(usesPortrait?(14+i*5):(24+i*9))+'px');n.style.setProperty('--speed',(5+i)+'s');n.onclick=()=>{$('town-tip').textContent=`${item[2]}: “${item[4]}”`};return n}
 function renderInventory(){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===townTab));let data=townTab==='decor'?TOWN_DECOR:townTab==='friends'?TOWN_FRIENDS:TOWN_PETS;let inv=$('town-inventory');inv.replaceChildren(...data.map(item=>{let ok=unlocked(item,townTab),b=el('button','inventory-item '+(!ok?'locked ':'')+(townSelection===item[0]?'active':''));b.innerHTML=`<span>${item[1]}</span>${item[2]}`;b.disabled=!ok;b.onclick=()=>{if(townTab==='decor'){townSelection=item[0];$('selected-item').textContent=`${item[2]} selected — click an empty plot to place it.`;renderInventory()}else $('town-tip').textContent=`${item[2]}: “${item[4]}”`};return b}))}
 function placeDecor(plot){if(!townSelection){$('selected-item').textContent='Choose a decoration from the chest first.';return}if(state.town.decor[plot]){delete state.town.decor[plot];$('selected-item').textContent='Decoration packed away. Choose another plot.'}else{state.town.decor[plot]=townSelection;$('selected-item').textContent='Placed! Click a decorated plot to pack it away.'}save();renderTown()}
 function campaignLevel(){return Math.max(0,state.unlocked-1)}
 function renderProfile(){let stars=Object.values(state.stars).reduce((a,b)=>a+b,0);$('profile-input').value=state.profile.name;$('profile-title').textContent=`${state.profile.name}’s Badge`;$('profile-level').textContent=campaignLevel()+1;$('profile-stars').textContent=stars;$('big-avatar').textContent=state.profile.avatar;$('big-avatar').className=`profile-avatar border-${state.profile.border}`;let avatars=$('avatar-picker');avatars.replaceChildren(...AVATARS.map(icon=>{let b=el('button','avatar-choice '+(icon===state.profile.avatar?'active':''),icon);b.onclick=()=>{state.profile.avatar=icon;renderProfile();renderHUD()};return b}));let borders=$('border-picker');borders.replaceChildren(...BORDERS.map(item=>{let available=campaignLevel()>=item[2],b=el('button',`border-choice border-${item[0]} ${state.profile.border===item[0]?'active':''} ${available?'':'locked'}`);b.title=available?item[1]:`Unlock at level ${item[2]}`;b.disabled=!available;b.onclick=()=>{state.profile.border=item[0];save();renderProfile()};return b}));let next=BORDERS.find(x=>x[2]>campaignLevel());$('border-status').textContent=next?`Next badge: ${next[1]} border at level ${next[2]}.`:'Every achievement border unlocked — legendary!'}
 function profileComingSoon(provider){modal(`<h2>${provider} sign-in</h2><p>This prototype keeps your profile on this device. To enable real ${provider} sign-in, add the app’s OAuth client ID and approved web address in the account integration configuration.</p><button onclick="document.getElementById('modal').classList.add('hidden')">Got it</button>`)}
 async function googleSignIn(){let cfg=window.PUZZLE_EMPIRE_AUTH||{};if(!cfg.googleClientId||cfg.googleClientId.includes('YOUR_')){modal('<h2>Google sign-in setup</h2><p>Add your public Web client ID to <b>auth-config.js</b>, then register your live site as an Authorized JavaScript origin in Google Cloud Console.</p><button onclick="document.getElementById(\'modal\').classList.add(\'hidden\')">Got it</button>');return}if(!window.google?.accounts?.id){await new Promise((resolve,reject)=>{let s=document.createElement('script');s.src='https://accounts.google.com/gsi/client';s.async=true;s.onload=resolve;s.onerror=reject;document.head.append(s)}).catch(()=>modal('<h2>Could not reach Google</h2><p>Check your connection and OAuth settings, then try again.</p>'))}if(!window.google?.accounts?.id)return;window.google.accounts.id.initialize({client_id:cfg.googleClientId,callback:googleCredential,auto_select:false});window.google.accounts.id.prompt()}
 async function googleCredential(response){let cfg=window.PUZZLE_EMPIRE_AUTH||{};try{let result=await fetch(cfg.profileApiUrl,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({credential:response.credential})});if(!result.ok)throw new Error('verification failed');let player=await result.json();state.profile.name=player.name||state.profile.name;state.profile.avatar=player.avatar||state.profile.avatar;save();renderProfile();modal('<h2>Connected!</h2><p>Your Google profile is now linked to Puzzle Empire.</p><button onclick="document.getElementById(\'modal\').classList.add(\'hidden\')">Continue</button>')}catch{modal('<h2>Sign-in needs a server</h2><p>Google returned an identity token, but the profile server is not available to verify and save it yet.</p><button onclick="document.getElementById(\'modal\').classList.add(\'hidden\')">Okay</button>')}}
 $('profile-badge').onclick=()=>{renderProfile();show('profile-screen')};$('profile-back').onclick=()=>{show('map-screen');renderMap()};$('save-profile').onclick=()=>{state.profile.name=$('profile-input').value.trim()||'Player';save();renderProfile()};$('big-avatar').onclick=()=>{$('avatar-picker').scrollIntoView({behavior:'smooth',block:'center'})};$('google-connect').onclick=()=>googleSignIn();$('facebook-connect').onclick=()=>profileComingSoon('Facebook');
 window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;$('install-game').hidden=false});$('install-game').onclick=async()=>{if(!installPrompt)return;installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;$('install-game').hidden=true};window.addEventListener('appinstalled',()=>{$('install-game').hidden=true});
 document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{townTab=b.dataset.tab;townSelection=null;renderInventory()});$('visit-town').onclick=()=>{renderTown();show('town-screen')};$('town-back').onclick=()=>{show('map-screen');renderMap()};
 document.querySelectorAll('.booster').forEach(b=>b.onclick=()=>{booster=b.dataset.power;document.querySelectorAll('.booster').forEach(x=>x.classList.toggle('selected',x===b));$('hint-text').textContent='Choose a gem to use your booster.'});$('royal-power').onclick=()=>{board.flat().forEach(x=>{if(Math.random()<.24)x.gem=-1});power=0;$('power-fill').style.width=0;$('royal-power').disabled=true;drop();renderBoard()};$('play-next').onclick=()=>start(state.unlocked);$('back-map').onclick=()=>{show('map-screen');renderMap()};window.PE={map:()=>{$('modal').classList.add('hidden');show('map-screen');renderMap()},town:()=>{$('modal').classList.add('hidden');renderTown();show('town-screen')},next:()=>{$('modal').classList.add('hidden');start(Math.min(30,current.id+1))},retry:()=>{$('modal').classList.add('hidden');start(current.id)}};renderMap();
})();

